//#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
//#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma once
#define UPDATE_CYCLE_IN_MILLISECONDS 100
#define INTERVAL 4
#include "Bot.h"


int EncoderDifference(MotorData data)
{

	return data.motorPort.rotation()-data.previousEncoderValue;
}

void trackVelocity(MotorData data)
{
	if(time1.time(msec) - data.previousTime >= UPDATE_CYCLE_IN_MILLISECONDS)
	{
		data.velocity = (float)(EncoderDifference(data)*40.0);
		data.previousEncoderValue = data.motorPort.position();
		data.previousTime = time1[T1];
	}
}

bool initiateStall(MotorData& motorData)
{

	const float startStallCheckThreshold = 5;
	const float checkStallThreshold = 5;

	if(motorData.stallData.isInitiated)
	{
		if(abs(motorData.velocity) >= checkStallThreshold)
		{
			writeDebugStreamLine("Velocity: %0.2f", motorData.velocity);
			return false;
		}
		else
		{
			writeDebugStreamLine("Stalling: %0.8f, Motor: %i", motorData.velocity, motorData.motorPort);
			return true;
		}
	}

	if(!motorData.stallData.isPassed)
	{
		if(abs(motorData.velocity) > startStallCheckThreshold)// also make it an and so that after it passes a certain velocity (1) it should then initiate
		{
			motorData.stallData.isInitiated = true;
			motorData.stallData.previousTime = time3.time(msec);
			motorData.stallData.isPassed = true;
		}
	}




	return false;

}

void realTime()
{

	int mask = INTERVAL - 1;
	int timeRemainder = mask & time3.time(msec);
	delay(INTERVAL - timeRemainder);
}



//task main()
//{
//	MotorMovementData left;
//	MotorMovementData right;

//	initMotorMovement(left, leftMotor);
//	initMotorMovement(right, rightMotor);

//	motor[leftMotor] = 100;
//	motor[rightMotor] = 100;

//	time1[T1] = 0;

//	while(true)
//	{
//		trackVelocity(left);
//		trackVelocity(right);

//		writeDebugStreamLine("Left: %0.2f", left.velocity*40);

//	}
//}
