

using namespace vex;


#define KP 0.5
#define GYRO_SPEED 50
#define BUFFER 20
#define MOVEMENT_INCREASE_FORWARD_P 3


#define C  1
#define D  2
#define E  3
#define F  4
#define G  5
#define A  6
#define B  12


vex::brain Brain;

// Motors
vex::motor rightArmMotor(PORT9, true);
vex::motor leftArmMotor(PORT3, false);

vex::motor RightFrontChassisMotor(PORT8, false);
vex::motor RightBackChassisMotor(PORT1, true);
vex::motor LeftFrontChassisMotor(PORT2, true);
vex::motor LeftBackChassisMotor(PORT7, false);

// Pneumatics
vex::pneumatic armSolenoid(PORT10);

// Sensors
vex::gyro firstStageArmGyro(PORT5);
vex::bumper backTouchSensor(PORT12);

// Controller
vex::controller Controller;

// Timer
vex::timer Timer;

//Gyro
vex::inertial Gyro;

vex::touchled touchLED(PORT4);

//vex::aivision AiVision(PORT2, aivision::ALL_AIOBJS);
vex::optical OpticalSensor(PORT11);
    

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAX_COMMAND_LENGTH 50
#define RADIUS_OF_ROBOT 80
#define RADIUS_OF_WHEEL 21
#include "MyHeaders.h"


void createCommands()
{
	bot.index = 0;

	// for(int i = 0; i < 4; i++)
	// {
		// initMoveByDegreeData(distanceToDegrees(100), distanceToDegrees(100), (TrapezoidalStates)Acc, (TrapezoidalStates)Acc);

			// initMoveByDegreeData(100,100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(-100,-100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(100,100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(-100,-100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initStopRecData();

		initMoveByDegreeData(degreesToMove(90), -degreesToMove(90), (TrapezoidalStates)Acc, (TrapezoidalStates)Acc);

			// initMoveByDegreeData(100,100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(-100,-100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(100,100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initMoveByDegreeData(-100,-100,(TrapezoidalStates)Acc,(TrapezoidalStates)Acc, true);
			// initStopRecData();
	// }

		//initMoveByDegreeData(distanceToDegrees(250), distanceToDegrees(450), Acc, Acc);



	initStopData();

	bot.index = 0;
}
void runCommands(Bot bot)
{
	BaseCommand& command = bot.commands[bot.index];
	switch(command.commandType)
	{
		case AttachMotorRec:
		{
			MoveAttachMotorData data;
			
			memcpy(&data, &command, sizeof(MoveAttachMotorData));

			configure(&data);

			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();


		}
		break;

		case MoveByDegreesRec:
		{
			RobotDrivetrainData data;

			memcpy(&data, &command, sizeof(RobotDrivetrainData));

			configure(&data);



			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();




		}
		break;

		/*
***********************************************		Your commands are being created while finalize is running *********************************************************************
		*/

		case LineFollowRec:
		{
			LineFollowData data;

			memcpy(&data, &command, sizeof(LineFollowData));

			configure(&data);

			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();


		}
		break;

		case LineFollow:
		{
			LineFollowData data;

			memcpy(&data, &command, sizeof(LineFollowData));

			configure(&data);

			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();

		}
		break;

		case AttachMotor:
		{
			MoveAttachMotorData data;

			memcpy(&data, &command, sizeof(MoveAttachMotorData));

			configure(&data);

			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();


		}
		break;

		case MoveByDegrees:
		{

			bool isLeftStalled = initiateStall((MotorData&)bot.left);
			bool isRightStalled = initiateStall((MotorData&)bot.right);
			bool isCenterStalled = initiateStall((MotorData&)bot.center);

			if(isLeftStalled ||
			   isRightStalled ||
			   isCenterStalled)
			{
				bot.isRecovery = true;
			}

			RobotDrivetrainData data;

			memcpy(&data, &command, sizeof(RobotDrivetrainData));

			configure(&data);

			if(!hasRan(&data)) return;

			cleanup(&data);

			finalize();
		}
		break;

		case StopRecovery:
		{
			bot.isRecovery = false;
		}
		break;

		case Stop:
		{
			bot.left.motorPort.stop();
			bot.right.motorPort.stop();
			bot.center.motorPort.stop();
		}
		break;
	}

}
void RecoveryChecker(bool& isCheckForRecovery, int startindex, int endindex)
{
	if(bot.index >= startindex && bot.index <= endindex)
	{
		isCheckForRecovery = true;
	}
	else
	{
		isCheckForRecovery = false;
	}
}


int main()
{
	bot.left.motorPort.initVexMotorGroup(LeftFrontChassisMotor, LeftBackChassisMotor);
	bot.right.motorPort.initVexMotorGroup(RightFrontChassisMotor, RightBackChassisMotor);
	bot.center.motorPort.initVexMotorGroup(rightArmMotor, leftArmMotor);
	bot.left.profile.previousPosition = 0;
	bot.right.profile.previousPosition = 0;
	bot.center.profile.previousPosition = 0;
	

	
	
	bot.isCheckForRecovery = false;
	bot.isRecovery = false;
	createCommands();

	while(true)
	{


		trackVelocity((MotorData&)bot.left);
		trackVelocity((MotorData&)bot.right);


		//if(SensorValue[sonar] < 24 && !bot.isRecovery && bot.isCheckForRecovery)
		//{
		//	bot.index++;
		//	//bot.isRecovery = true;
		//}

		RecoveryChecker(bot.isCheckForRecovery, 0, 40);
		runCommands((Bot&)bot);


		realTime();
	}


}
